### ISSUE TITLE
Inflexible sizing

### ISSUE THREAD

**Issue by tlitookilakin** [flarive/Neumorphism.Avalonia#12]
Because the button styling includes explicit `Width` and `Height` setters, buttons are always fixed size when using this theme; they cannot be flexibly sized- they can't be shrunk/grown to fit their contents or available space.

Switching this to `MinWidth` and `MinHeight` is a better approach I think, because it will maintain a nice "default" size, and can still be easily altered to suit a given layout.

This may also be an issue on other widgets, but it is most noticeable on buttons.

**Comment by flarive** [comment]
Hey, thanks for this feedback !
Ok, i'm going to try to solve that issue soon...

**Comment by flarive** [comment]
Hello...
Sorry for the long response delay.

I finally found a simple way to do that :
Just add Width="NaN" to your button to have flexible auto sizing fitting the content.

May be Width="NaN" could become the default width in my button theme, not sure, i have to think about it...

**Comment by flarive** [comment]
Closing this issue, please reopen it if needed.
