### ISSUE TITLE
Terms of use

### ISSUE THREAD

**Issue by fomines** [flarive/Neumorphism.Avalonia#14]
Hi!
What are the conditions for using your theme for a commercial organization? 
The rights to the developed software, in which we want to use your theme, belong to our company. The software is planned to be sold and resold, as well as provide free and paid access to the company's customers.

**Comment by flarive** [comment]
Hi !

Could you just present me quickly the software where Neumorphism Avalonia will be used.
I'm just curious :)
You can send me an email to flarive[at]hotmail.com

Do you use (or plan to use) Avalonia 0.11 ? Or are you using Avalonia 0.10.x ?

Best regards

Eviral

**Comment by fomines** [comment]
Hello, Eviral.
Thanks for the feedback. We sent more detailed information to the mail from email "usanov.serg". Waiting for an answer. Thank's)
