### ISSUE TITLE
support avalonia 11 rc 1.1

### ISSUE THREAD

**Issue by cesarchefinho** [flarive/Neumorphism.Avalonia#15]
pplease, can you Add support to avalonia 11 rc 1.1

thanks a lot!

It is a beautiful theme

**Comment by flarive** [comment]
Hello, thanks :)
I'm currently working on it.
It's quite a big work because i have to rewrite a lot of things.
I hope i will have finished in a few weeks.

Eviral

**Comment by cesarchefinho** [comment]
you can write to me at cesarchefinho@gmail.com

**Comment by cesarchefinho** [comment]
also i already sponsor the project at patreon

**Comment by flarive** [comment]
Neumorphism Avalonia 0.5.0 for Avalonia 11 released !
