### ISSUE TITLE
Could not find control 'PART_MinimizeButton'.' when ExtendClientAreaToDecorationsHint="True"

### ISSUE THREAD

**Issue by MohammadHadi2031** [flarive/Neumorphism.Avalonia#29]
How to reproduce? 
Just add ExtendClientAreaToDecorationsHint="True" in [AboutWindow](https://github.com/flarive/Neumorphism.Avalonia/blob/8c79e73480e0e97356b2faa483945800f356a3a3/Neumorphism.Avalonia.Demo/Windows/AboutWindow.axaml#L8C1-L8C1) then run and open about window

**Comment by flarive** [comment]
Hello,
What is the purpose of "ExtendClientAreaToDecorationsHint" ? I have never eared about it :(
Anyway, going to try to fix it :)

**Comment by flarive** [comment]
Ahh i found it myself...
https://docs.avaloniaui.net/docs/tutorials/music-store-app/creating-a-modern-looking-window

**Comment by flarive** [comment]
Bug fixed, just submited the fix into master...
Here is how it looks with the fix (no more exception) :)

![MohammadHadi2031](https://github.com/flarive/Neumorphism.Avalonia/assets/7724904/e57fc958-9580-4d7c-95c2-5474bd7ac3a4)

**Comment by MohammadHadi2031** [comment]
Great! Maybe we can have neomorphism for caption buttons too 🤔🤔? Thanks BTW

**Comment by flarive** [comment]
You're right, CaptionButtonss.xaml is not themed for Neumorphism for the moment...
Will try to do it quite soon (have to find some references/inspiration guidelines on the web)
